# Generated by Django 5.1 on 2024-08-29 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_people', models.CharField(max_length=255)),
                ('datetime_appear', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
